{% set name = "b2btools" %}
{% set version = "3.0.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b3c9f10c10c8a12c390a79016e01b7e4d165bf1c94dce48e72d31891cb552c29

build:
  number: 0
  entry_points:
    - b2bTools = b2bTools.__main__:main
    - b2btools = b2bTools.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  run_exports:
    - {{ pin_subpackage('b2btools', max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }} # [linux]
    - {{ compiler('cxx') }} # [linux]
    - clangdev  # [osx]
  host:
    - python
    - pip
    - cython ==0.29.37 # [py < 311]
    - cython # [py >= 311]
  run:
    - python
    - hmmer
    - t-coffee
    - biopython >=1.81 # [py <= 39]
    - biopython >=1.83 # [py >= 310]
    - matplotlib-base >=3.5.3
    - numpy ==1.21 # [py37]
    - numpy ==1.24 # [py == 38 or py == 39]
    - numpy ==1.26 # [py > 39]
    - pandas >=1.1, <2.3
    - pomegranate >=0.14, <1.0
    - requests >=2.0 # [py <= 39]
    - requests >=2.31.0 # [py > 39]
    - scikit-learn ==1.0.2 # [py <= 310]
    - scikit-learn ==1.4.1.post1 # [py > 310]
    - scipy ==1.7.3 # [py == 37]
    - scipy ==1.10.1 # [py == 38 or py == 39]
    - scipy ==1.12.0 # [py > 39]
    - pytorch >=1.11.0,<=1.13.1 # [py <= 310]
    - pytorch >=2.2.0 # [py > 310]
    - urllib3 >=1.26.6

test:
  imports:
    - b2bTools
    - b2bTools.general
    - b2bTools.general.bmrb
    - b2bTools.general.ccpn
    - b2bTools.general.ccpn.format
    - b2bTools.general.ccpn.format.general
    - b2bTools.general.ccpn.format.nmrStar
    - b2bTools.general.ccpn.general
    - b2bTools.general.ccpn.universal
    - b2bTools.general.parsers
    - b2bTools.multipleSeq
    - b2bTools.nmr
    - b2bTools.nmr.shiftCrypt
    - b2bTools.nmr.shiftCrypt.models
    - b2bTools.nmr.shiftCrypt.shiftcrypt_pkg
    - b2bTools.singleSeq
    - b2bTools.singleSeq.Agmata
    - b2bTools.singleSeq.Agmata.bin
    - b2bTools.singleSeq.Agmata.marshalled
    - b2bTools.singleSeq.Agmata.sources
    - b2bTools.singleSeq.DisoMine
    - b2bTools.singleSeq.DisoMine.vector_builder
    - b2bTools.singleSeq.DisoMine.vector_builder.psipred
    - b2bTools.singleSeq.DisoMine.vector_builder.psipred.bin
    - b2bTools.singleSeq.DisoMine.vector_builder.psipred.bin.linux
    - b2bTools.singleSeq.DisoMine.vector_builder.psipred.bin.osx
    - b2bTools.singleSeq.DisoMine.vector_builder.psipred.data
    - b2bTools.singleSeq.DynaMine
    - b2bTools.singleSeq.DynaMine.models
    - b2bTools.singleSeq.DynaMine.models.backbone
    - b2bTools.singleSeq.DynaMine.models.coil
    - b2bTools.singleSeq.DynaMine.models.helix
    - b2bTools.singleSeq.DynaMine.models.ppII
    - b2bTools.singleSeq.DynaMine.models.sheet
    - b2bTools.singleSeq.DynaMine.models.sidechain
    - b2bTools.singleSeq.EFoldMine
    - b2bTools.singleSeq.EFoldMine.models
    - b2bTools.singleSeq.PSPer
    - b2bTools.singleSeq.PSPer.hmmer_research
    - b2bTools.singleSeq.PSPer.marshalled
    - b2bTools.singleSeq.PSPer.source
    - b2bTools.wrapper_source
  commands:
    - b2bTools --help
    - b2bTools --version
    - b2bTools --input_file test.singleseq.fasta --output_json_file test.singleseq.out.json --output_tabular_file test.singleseq.out.csv --metadata_file test.singleseq.metadata.csv --mode single_seq --dynamine --disomine --efoldmine --agmata --psper
    - b2bTools --input_file test.msa.fasta --output_json_file test.msa.out.json --output_tabular_file test.msa.out.csv --metadata_file test.msa.metadata.csv --distribution_json_file test.msa.dist.json --distribution_tabular_file test.msa.dist.csv --mode msa --dynamine --disomine --efoldmine --agmata --psper
  files:
    - test.singleseq.fasta
    - test.msa.fasta

about:
  home: "https://bio2byte.be/b2btools"
  license: 'GNU General Public License v3 (GPLv3)'
  license_family: GPL3
  license_file: LICENSE
  summary: "bio2Byte software suite to predict protein biophysical properties from their amino-acid sequences"
  description: |
    This package provides you with structural predictions for protein sequences made by the Bio2Byte group which researches the relation between protein sequence and biophysical behavior.
    List of available predictors:
      - Dynamine: Fast predictor of protein backbone dynamics using only sequence information as input. The version here also predicts side-chain dynamics and secondary structure predictors using the same principle.
      - Disomine: Predicts protein disorder with recurrent neural networks not directly from the amino acid sequence, but instead from more generic predictions of key biophysical properties, here protein dynamics, secondary structure, and early folding.
      - EfoldMine: Predicts from the primary amino acid sequence of a protein, which amino acids are likely involved in early folding events.
      - AgMata: Single-sequence-based predictor of protein regions that are likely to cause beta-aggregation.
      - PSPer: PSP (Phase Separating Protein) predicts whether a protein is likely to phase-separate with a particular mechanism involving RNA interacts (FUS-like proteins).
  doc_url: https://pypi.org/project/b2bTools/
  dev_url: http://bitbucket.org/bio2byte/b2btools_releases

extra:
  author: Wim Vranken <wim.vranken@vub.be>
  recipe-maintainers:
    - Adrián Díaz <adrian.diaz@vub.be> (@agdiaz)
    - Jose Gavaldá-García <jose.gavalda.garcia@vub.be> (@GavaldaGarcia)
  maintainers:
    - Adrián Díaz <adrian.diaz@vub.be> (@agdiaz)
    - Jose Gavaldá-García <jose.gavalda.garcia@vub.be> (@GavaldaGarcia)
  identifiers:
    - doi:10.48550/arXiv.2405.02136 # bioRxiv preprint
    - biotools:b2btools
