{% set name = "constava" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/constava-{{ version }}.tar.gz
  sha256: 25b3c6f1cacdb19e3352192ff3a0318782fcf071cee8a863bd806beb23a8ab74

build:
  number: 0
  entry_points:
    - constava = constava.__main__:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv"
  run_exports:
    - {{ pin_subpackage('constava', max_pin="x") }}

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - mdanalysis
    - numpy
    - pandas
    - scikit-learn

test:
  imports:
    - constava
    - constava.Constava
  commands:
    - constava --help

about:
  home: https://bio2byte.be
  summary: Calculate conformational states probability and variability from a protein structure ensemble
  description: |
    ConStaVa is a tool for the probabilistic interpretation of large conformational ensembles
    (e.g. from MD simulations or for intrinsically disordered proteins). Through analysis of
    phi/psi angle distributions, it detects six conformational states and calculates the associated
    'conformational state variability'. It so moves away from traditional fixed secondary structure
    interpretation of models to a more ensemble-oriented interpretation that is useful for dynamic
    regions of proteins.
    Contact (via email): bio2byte@vub.be
  license: GPLv3
  license_file: LICENSE
  dev_url: https://github.com/bio2byte/constava
  doc_url: https://pypi.org/project/constava/
  doc_source_url: https://github.com/Bio2Byte/constava/blob/main/README.md

extra:
  author: Wim Vranken <wim.vranken@vub.be>, Jose Gavalda-Garcia <jose.gavalda.garcia@vub.be>, David Bickel <david.bickel@vub.be>, Joel Roca-Martinez <joel.roca.martinez@vub.be>, Daniele Raimondi <daniele.raimondi@kuleuven.be>, Gabriele Orlando <gabriele.orlando@kuleuven.be>
  recipe-maintainers:
    - Adrián Díaz <adrian.diaz@vub.be> (@agdiaz)
    - David Bickel <david.bickel@vub.be> (@aethertier)
    - Jose Gavaldá-García <jose.gavalda.garcia@vub.be> (@GavaldaGarcia)
  maintainers:
    - David Bickel <david.bickel@vub.be> (@aethertier)
    - Jose Gavaldá-García <jose.gavalda.garcia@vub.be> (@GavaldaGarcia)
  identifiers:
    - doi:10.1101/2023.07.24.550386 # bioRxiv preprint
